Crunch-io/rcrunch

README.md
https://www.pivotaltracker.com/story/show/128534261
=> add info about installing correct version of R

NEWS.md, R/R-to-variable.R, man/toVariable.Rd, tests/testthat/test-add-variable.R
=> toVariable can now handle AsIs classes being passed to it.

R/make-array.R, man/makeArray.Rd, tests/testthat/test-derive-array.R
deriveArray() now can accept (and will use!) a selections argument. When selections is provided, a multiple response variable will be derived instead of a categorical array. Now with more CI goodness.
=> Dichotomize derive array 148685747

R/AllGenerics.R, R/export-dataset.R, man/exportDataset.Rd
see https://github.com/r-lib/pkgload/issues/45
=> Updated write.csv definition to better dispatch appropriately 

inst/crunch-test.R, tests/testthat/test-export-dataset.R
now that write.csv is properly dispatched.
=> removed skip_if_devtools_loaded 

tests/testthat/test-merge-datasets.R
Explicit order checking, and details about reproduction of the transient bug.
=> Append test expansion

NEWS.md, R/append-dataset.R, R/batches.R, R/new-dataset.R, man/appendDataset.Rd, tests/testthat/test-append-arrays.R, tests/testthat/test-append-conflicts.R, tests/testthat/test-append-subset.R, tests/testthat/test-appending.R, tests/testthat/test-dataset-stream.R
=> Deprecate `autorollback` and `savepoint`when appending to reflect the API change

NEWS.md, R/case-variables.R, tests/testthat/test-case-variables.R
Incredibly minor, added one edge-case catch, and a test to ensure that it is caught. Closes #158
=> Added a check that there are no unnamed elements in each case.

R/api.R, R/get-datasets.R, inst/app.crunch.io/api/datasets/1.json, inst/app.crunch.io/api/datasets/1streaming.json, inst/app.crunch.io/api/datasets/3.json, tests/testthat/test-auth.R, tests/testthat/test-get-datasets.R, tests/testthat/test-new-dataset.R, tests/testthat/test-user.R
I was working on a new feature in httptest and noticed that this could be simpler and do less work. 
I also deleted a couple of unnecessary checks elsewhere. The changes in [test-new-dataset.R](https://github.com/Crunch-io/rcrunch/commit/bf30cdce8cba#diff-b1fe15667db71be5af9a26a5a256aff2) are just deleting two tests and reducing indentation.
=> Don't bother with dataset catalog if loadDataset(url)

NEWS.md, R/insertions.R, R/subtotals-and-headings.R, R/transform-calculate.R, man/SubtotalsHeadings.Rd, tests/testthat/test-cube-transforms.R, tests/testthat/test-insertions.R, tests/testthat/test-subtotals-and-headings.R, vignettes/abstract-categories.Rmd
The position argument takes top/bottom/relative as values. If relative (the default) is given, then an after argument must be present.
=> Subtotals and headings now have a position argument

tests/testthat/test-cube-mr.R
No code changed, but adding tests/expectations for the benefit of others.
=> Added CAT x MR fixtures and expectations

_pkgdown.yml, pkgdown/extra.css
This PR changes bootswatch template and adds new styles that work together with new crunch website once is launched.
https://www.pivotaltracker.com/story/show/156091216
=> New theme and css styles 

tests/testthat/test-merge-datasets.R
See:
- https://www.pivotaltracker.com/story/show/154829831
=> [#154829831] - Hier changes for hidden variables

tests/testthat/test-merge-datasets.R
See:
- https://www.pivotaltracker.com/story/show/157298702
=> [#157298702] - Hier __hidden__ group

R/variable-delete.R, tests/testthat/test-variable-delete.R
=> Only delete unique variables urls

R/folders.R, R/show.R, tests/testthat/test-folder-projects.R
Minor style changes that I missed in project folders transition
=> Style cleanup projects

R/crunchbox.R, R/cube-query.R, man/crtabs.Rd, man/crunchBox.Rd, man/dataset-to-R.Rd, man/setName.Rd, man/setNames.Rd, tests/testthat/test-crunchbox.R
=> Add 'weight' argument to crunchBox and to its API request

R/R-to-variable.R, man/toVariable.Rd, tests/testthat/test-add-variable.R
=> Updated to conform to Haven's breaking changes.

R/change-category-id.R, tests/testthat/test-categories.R
=> Corrected validation code for changeCategoryID()

R/as-data-frame.R, tests/testthat/test-as-data-frame.R
=> Let variables with non-DF name conformant aliases work with as.data.frame

DESCRIPTION
I replaced you as `cre`, which is how CRAN decides to email. Let me know if that's not what you want, but I remember in my interview you joking that you wanted out of those responsibilities. Also, not sure if you consider the author order important, do you want to be last author?
=> Add me as author

R/slides.R
=> valuelabels redux

NEWS.md, R/multitables.R, tests/testthat/test-multitables.R
we forgot to pass the `...` so `is_public` wasn't used
=> multitables passes `...`, fixes #424

NEWS.md, R/multitables.R, R/tab-book.R, inst/app.crunch.io/api/datasets/1/multitables/4de322.json, inst/app.crunch.io/api/datasets/1/multitables/ed30c4.json, inst/app.crunch.io/api/datasets/1/multitables/f33123.json, inst/app.crunch.io/api/datasets/3/multitables/ed30c4.json, man/tabBook.Rd, tests/testthat/test-multitables.R
This includes #425 because I messed up the git. 
The tests check the shape of the request now (you had added logic about filters, I added selected variables, options in the new endpoint, and shape + warning of deprecated endpoint).
=> Tabbook new endpoint fixes #420

DESCRIPTION, R/tab-book.R
=> Increase retry wait refs #438

DESCRIPTION, NEWS.md, inst/httptest/redact.R, tests/testthat/test-cube-bases.R
minor stuff, still haven't heard back from CRAN's win builder, but will merge into master anyways.
=> cleanups before cran submission

NEWS.md, R/case-when-variable.R, R/fill-variable.R, man/fillExpr.Rd, man/makeCaseWhenVariable.Rd, tests/testthat/test-case-when-variable.R, tests/testthat/test-fill-variable.R
Add numeric_fill and expose it to use through `caseWhenExpr()`
=> Numeric case when

tests/testthat/app.crunch.io/api/progress2/2.json, tests/testthat/test-progress.R
kill a tiny bit of joy (and fix #493)
=> better test for progress failure

tests/testthat/test-case-when-variable.R
add integration tests for case when
waiting for https://www.pivotaltracker.com/n/projects/2172644/stories/174198825 to ship
=> case when integration tests

tests/testthat/test-cube-with-expression.R
=> trailing test coverage for #521

tests/testthat/test-subtotals-and-headings.R
remove integration tests that use headings, because API will no longer accept them going forward.
=> No headers 178488583

R/projects.R, man/newProject.Rd, man/projects.Rd
help fix this up; probably needs more work but we want to reduce if not eliminate the word project
=> reduce if not eliminate the use of the word project

Makefile, docker/jenkins/Dockerfile.rcrunch
Trying to improve rcrunch in Jenkins
=> Dockerfile tweak 186333897
