R/api.R, R/export-dataset.R, R/tab-book.R, tests/testthat/test-api.R
I wanted to touch up the branch where you had added the retry function while I was on the plane, but I didn't have it in my local checkout, so I just redid it. Got a better test for `retry` and factored out a `crDownload` function.
=> Add a retry to deal with CDN delay on download

R/categories.R, man/changeCategoryID.Rd, tests/testthat/test-categories.R
Added tests of numeric value changes when using `changeCategoryID()` `changeCategoryID()` no longer always makes the numeric value the same as the new ID. This addresses issue #103
=> Fixed `changeCategoryID()` to not always update the numeric value of the category.

R/geo.R, inst/WORDLIST, inst/app.crunch.io/api/geodata.json, inst/app.crunch.io/api/geodata/duplicate_prop.json, inst/app.crunch.io/api/geodata/no_metadata.json, man/addGeoMetadata.Rd, tests/testthat/test-geo.R
`addGeoMetadata` now will automatically match when a geodatum has duplicate properties.
=> addGeoMetadata updates

R/dataset.R, R/get-datasets.R, inst/app.crunch.io/api/datasets/1.json, inst/app.crunch.io/api/datasets/1streaming.json, man/refresh.Rd, tests/testthat/test-dataset-entity.R
Drop the catalog cache, but refresh the entity object with just the entity.
=> Refresh a dataset entity without requesting a dataset catalog

NEWS.md, R/cube-dims.R, tests/testthat/cubes/univariate-categorical-like-selected.json, tests/testthat/test-cube-basic.R, tests/testthat/test-cube-mr.R
For cube methods with multiple response variables, we need to identify which dimension is the selected dimension (generally represented as a categorical with the categories Selected, Not selected, and No data). The method to determine if a dimension was selected was overly aggressive, and would identify categorical variables that had those categories as a selected dimension, which broke a number of display methods for those categorical variables.
This change only marks a dimension as selected if it has the magic Selected, Not selected, No data categories and if its alias matches a multiple response dimension. This should be true of all multiple response using the `as_selected` zz9 function.
In testing, I added some `test_path()`s around cube fixtures for easier interactive testing.
=> Fixes a bug where a categorical variable could be confused with the selected dimension of a Multiple Response

R/AllClasses.R, R/cube-dims.R, R/cube-transforms.R, R/pretty-print.R, R/show.R, R/transform.R, man/Transforms.Rd, tests/testthat/cubes/catarray-with-transforms.json, tests/testthat/test-cube-basic.R, tests/testthat/test-cube-dims.R, tests/testthat/test-cube-mr.R, tests/testthat/test-cube-transforms.R, tests/testthat/test-insertions.R, tests/testthat/test-subtotals-and-headings.R
This PR addresses some rough edges of Subtotals/Heaidngs:
* `Insertions` objects with `Subtotal`s and `Heading`s that have category names (instead of ids) for `after` or `categories` now display nicely, without error, like other abstract categories
* Cubes with categorical arrays or multiple response actively suppress transforms calculations for now (until we have 2d calculation and displaying working)
* cube dimensions that have subreferences are now referred to as `subvariable_items` instead of `multiple_response` since they can be both categorical arrays and multiple response.
* users can now set transforms on CrunchCubes directly.
=> Clean up for Subtotals and Headings / Transforms

DESCRIPTION, tests/spelling.R
Thank you for using the spelling package. The new version `spelling 1.1` stores the language in the package `DESCRIPTION` field.
=> Store spelling language in package DESCRIPTION

tests/testthat/test-active-filter.R, tests/testthat/test-as-data-frame.R, tests/testthat/test-conditional-transform.R
I've added `skip_locally()` to operations that call `as.data.frame(, force = TRUE)` since those now execute with an export and the local setup doesn't serve exports well. DevOps says they are working on improving that situation, but for now, this will let those tests not fail noisily against a local backend. Because of the way `skip_locally()` works, testing against other backends (alpha/stable/app) will not skip, so we're still covered with jenkins and manual local tests against non-local backends. 
I also removed a skip for an unrelated backend bug that has been fixed.
=> Export test skipping (locally only)

tests/testthat/helper-expectations.R, tests/testthat/print-folders.R, tests/testthat/test-active-filter.R, tests/testthat/test-api.R, tests/testthat/test-append-arrays.R, tests/testthat/test-append-conflicts.R, tests/testthat/test-append-debug.R, tests/testthat/test-batches.R, tests/testthat/test-categories.R, tests/testthat/test-compare.R, tests/testthat/test-crunchbox.R, tests/testthat/test-cube-basic.R, tests/testthat/test-cube-transforms.R, tests/testthat/test-dataset-entity.R, tests/testthat/test-derive.R, tests/testthat/test-exclusion-filter.R, tests/testthat/test-expressions.R, tests/testthat/test-filters.R, tests/testthat/test-fork.R, tests/testthat/test-geo.R, tests/testthat/test-insertions.R, tests/testthat/test-merge-datasets.R, tests/testthat/test-multitables.R, tests/testthat/test-progress.R, tests/testthat/test-projects.R, tests/testthat/test-subtotals-and-headings.R, tests/testthat/test-variable-catalog.R, tests/testthat/test-variable-folders.R, tests/testthat/test-variable-order.R, tests/testthat/test-variable-transforms.R
Add `expect_prints()` instead of overriding `testthat::expect_output()`. (History: `testthat::expect_output()` used to print the objects you passed it but stopped a couple of versions ago. This function overloading was to maintain compatibility across versions.)
Default in `expect_prints` is `fixed=TRUE`, unlike the standard `testthat` functions (including `expect_output`). It seemed that for our needs, regexp matching of output was the exception not the rule. Doing this allowed me to fold the old `expect_fixed_output()` into `expect_prints` too.
Unit/mock tests pass but I didn't have a network connection on the airplane to run the integration tests, so there may be some tests in there that need `fixed=FALSE` added.
=> Test cleanup: expect_prints

R/subtotals-and-headings.R, man/SubtotalsHeadings.Rd, tests/testthat/test-subtotals-and-headings.R
Small change to set default `after` value for subtotal if the position is relative and after is not supplied. If `after` is not supplied it defaults to the category specified in the `categories` argument to `Subtotal`. Last in this case refers to the order of the variable's categories, not the order that those categories are supplied to `Subtotal`.
=> Changed default behaviour for after

R/categories.R, R/expressions.R, R/show.R, R/zcl.R, man/expressions.Rd, tests/testthat/test-combine-categories.R, tests/testthat/test-exclusion-filter.R, tests/testthat/test-expressions.R, tests/testthat/test-zcl.R
And map %in% to `selected`, the new function that will drop missingness, just as `%in%` does in R.
=> Distinguish %in% and ==, as they should be

R/make-array.R, tests/testthat/test-make-array.R
Raise error when user tries to derive an MR from a delimited categorical. This is just a quick fix, and I raised an issue with next steps for this area https://github.com/Crunch-io/rcrunch/issues/246
=> makeMRFromText categorical bug

R/shoji-catalog.R, tests/testthat/test-hide-variables.R, tests/testthat/test-variable-catalog.R
See https://www.pivotaltracker.com/story/show/157283138 for an error report and https://crunch-io.slack.com/archives/C8HLAUW23/p1525372333000744 for discussion. Basically, `ds <- hideVariables(ds, c("gender", "gender")` would make an invalid request. This fix adds validation that catches that and some other possible scenarios.
=> setIndexSlot should check for duplicate URLs

R/weight.R, tests/testthat/test-weighting.R
=> Fix `makeWeight()` to send category ids and not integers from 1

R/conditional-transform.R, tests/testthat/test-conditional-transform.R
I've loosened the validation, and added some tests. I had to do a bit more work to get the dataset object (it now checks the RHSes, LHSes, and data arugments — one of those must have at least one dataset reference in it — I doubt anyone will run into this because doing `conditionalTransform(TRUE~"foo", name = "my new all foo variable")` is a lot more work than `ds$all_foo <- "foo"` but in case someone finds themselves there).
=> Allow conditional transforms with LHSes and RHSes that don't have Crunch expressions

tests/testthat/test-crunchbox.R, tests/testthat/test-projects.R, tests/testthat/test-user.R
All skips have corresponding tickets associated with them.
=> Skip (locally) tests that don't work against a local backend

README.md
We got rid of this right? We can remove a “build failing” badge?
=> dump appveyor

NEWS.md, R/tab-book.R, man/tabBook.Rd, tests/testthat/test-multitables.R
Adds ability to set override active filter on tabbook export.
~As I pushed, realized we might want to allow CrunchExpr in the filter argument, worth it?~
No, because CrunchExprs didn't work in old code.
=> Add filter argument to tabbook

inst/httptest/redact.R, inst/httptest/start-vignette.R
This fix exists on at least one branch already, but I want to push it into master so Brandon can use it when making mocks for cruntabs.
The old regex has problems because there is a "progress" item in the views now, and so what originally looks like this:
```
"progress": "https://app.crunch.io/api/progress/",
"search": "https://app.crunch.io/api/search/",
```
with the old regex gets converted to:
```
"progress": "https://app.crunch.io/api/progress//app.crunch.io/api/search/",
```
=> fix regex for progress removal in http redaction

R/slides.R, man/analysis-methods.Rd, tests/testthat/test-decks.R
When crunch doesn't define a method for filter, filter goes to next filter on namespace and tries that.
``` r
suppressPackageStartupMessages(library(crunch))
identical(filter(1:100, rep(1, 3)), stats::filter(1:100, rep(1, 3)))
#> [1] TRUE
```
``` r
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(crunch))
identical(filter(mtcars, cyl == 4), dplyr::filter(mtcars, cyl == 4))
#> [1] TRUE
```
=> filter escape hatch

NEWS.md, R/dataset-update.R, man/crunch-extract.Rd, tests/testthat/test-derive.R
Was explicitly forbidden before, but the API must have been updated so that it works:
Can now do something like:
```
ds$z <- ds$y == "a"
```
=> direct assignment of logical expression, fixes #286

inst/crunch-test.R
Three years ago, [several functions were renamed](https://enpiar.com/r/httptest/news/#other-big-changes-and-enhancements) in the `httptest` 3.0.0 release for consistency with `httr` and `testthat`. Function aliases with the old naming were kept to avoid breaking packages, but in the [upcoming `httptest` 4.0.0 release](https://github.com/nealrichardson/httptest/issues/53), these deprecated functions are being removed. This PR updates your package to use the functions that will remain in the 4.0.0 release.
We plan to submit the `httptest` update to CRAN at the end of January. To avoid any potential nastygrams from CRAN, it would be ideal if you can update your package on CRAN with this change before then. Thanks!
=> Replace httptest::with_mock_API with with_mock_api

inst/crunch-test.R
Small fix I discovered on the numeric array work to have lines reported during integration test failures. I can't say I totally understand why this works, but am pretty confident that it both gives the correct line number and does the fixture cleanup that the original code was trying to make happen.
Before:
```
══ Failed ══════════════════════════════════════════════════════════════════════════════════════════════════════════════
── 1. Failure (???): There are no test code errors ─────────────────────────────────────────────────────────────────────
`stop(e$message)` threw an error.
Message: something broke
Class:   simpleError/error/condition
Backtrace:
1. testthat::expect_error(stop(e$message), NA)
2. testthat:::quasi_capture(...)
5. rlang::eval_bare(quo_get_expr(.quo), …
```
=> Fix for integration test failure reporting

R/AllClasses.R, R/show.R, R/subvariables.R, R/variable-type.R, R/variable.R, man/Subvariables.Rd, man/crunch-extract.Rd, man/describe-catalog.Rd, man/unbind.Rd, tests/testthat/test-subvariables.R
Trying to split out the numeric array work into smaller PRs. This is preparatory work to make an `ArrayVariable` super (virtual) class and improve the array variable printing. 
Some examples of the new array variable printing printing. It now shows both the alias and the name (instead of just the name), alligns the start of the names, and truncates if the name is going to extend past the edge of the console.
```
ds$array1
#> First array (categorical_array)
#> Subvariables:
#>   $var                 | a variable name
#>   $a_longer_var_alias  | another variable name that is so long that it will get trun...
```
=> Array cleanup

R/formula.R, R/show.R, tests/testthat/test-cube-mr.R, tests/testthat/test-cube-with-expression.R, tests/testthat/test-formula.R, tests/testthat/test-multitables.R, vignettes/crunch/5/api/datasets/c25696/cube-3c9429.json
Use the `dimension` function to specify the dimensions of an array variable rather than the deprecated "each" function. Most of these changes were to fixtures.
=> Deprecate "each"

R/make-array.R, R/variable-type.R, man/describe-catalog.Rd, tests/testthat/test-expressions.R, tests/testthat/test-make-array.R, tests/testthat/test-variable-type.R
Better error message for the case that you expect  `deriveArray` and `makeArray` to have subvariables in `...` argument and re-allow lists of variables to be used in `makeArray()`.
=> Array tweaks

R/cube-dims.R, R/formula.R, man/getDimTypes.Rd, tests/testthat/test-cube-dims.R
A simple way to handle numeric arrays in cubes, when the first measure can be identified as a numeric array (the measure has metadata with object type that has subvariables, matching what the cr.cube does) we inflate a single "measure axis" that comes with most measures of numeric arrays and adds it as an equal to the other cube dimensions.
I see 2 issues with this approach:
1) (probably not a big deal): This approach can get confused with complex cubes with some measures based on a numeric array and others aren't.
2) (probably will need a different strategy when as we continue to support num arrays): Not all measures based on numeric arrays have one dimension, eg covariance matrix has 2, so I think we need a separate the concepts of "measure axis" vs "cube dimension" and keep track of …
=> Num array cube

DESCRIPTION, R/cube-dims.R, R/formula.R, R/show.R, R/tab-book.R, man/getDimTypes.Rd, mocks/app.crunch.io/api/datasets/1/multitables/apidocs-tabbook.json, tests/testthat/app.crunch.io/api/datasets/1/multitables/apidocs-ca-mr-tabbook.json, tests/testthat/app.crunch.io/api/datasets/1/multitables/apidocs-mr-ca-tabbook.json, tests/testthat/test-cube-dims.R, tests/testthat/test-multitables.R
Includes #537
When adding support for numeric arrays noticed a few problems with how tabbook pages are printed (because of the way we rearrange cubes) and we'll also have to rearrange the numeric-array dimension.
=> Fixes for tabbook found when adding support for numeric arrays

R/cube-query.R, R/formula.R, R/slides.R, man/analysis-methods.Rd, man/crtabs.Rd, man/display-settings.Rd, man/newSlide.Rd, tests/testthat/test-cubes.R, tests/testthat/test-formula.R
Can now do:
```r
slide <- newSlide(deck, ~scorecard(ds$enjoy_mr, ds$another_mr), title = "scorecard slide")
```
I continued to stretch the formula notation, at some point this may break, but for now I think it's nice because it means you can use the scorecard query other places that expect a query too (eg in `crtabs`).
Left to do:
documentation (not sure where to put it)
=> Scorecard query

R/variable-folder.R, R/variables.R
I believe this fixes a cryptic bug that a user experienced. I the API returned a folder in the private/secure folder had an object with no type and so when trying to get the variables of a dataset, this line was a length 0 in an `if` statement:
https://github.com/Crunch-io/rcrunch/blob/095d861434d9329ac0e5f3890b67a2adc07be171/R/variable-folder.R#L30
Error was: 
```
Error in h(simpleError(msg, call)) : 
error in evaluating the argument 'table' in selecting a method for function '%in%': error in evaluating the argument 'x' in selecting a method for function 'variables': argument is of length zero
```
=> Guard against bad data from API in a folder

R/formula.R, R/slides.R, tests/testthat/test-decks.R, tests/testthat/test-formula.R, vignettes/deck-cookbook.Rmd
block array categories dimension in first dimension of a slide's analysis because whaam chokes on it
allow `selectCategories()` in the query so users can convert cat arrays into MRs like whaam does
=> reconcile slide queries from rcrunch with whaam behavior

R/api.R, tests/testthat/test-progress.R
I saw this may not address the problem we're currently facing, but I think this is still worth it:
Now if there's an error during `pollProgress()` it will message the progress url. 
Also added option `crunch.show.progress.url`, which always messages it. I'm not sure it's super useful, but will give us this capability in the future.
=> message progress url options

R/shoji-catalog.R
Fixes a bug where we couldn't print a deck catalog because it's `dashboard` key was an empty JSON dict.
```r
x <- jsonlite::fromJSON("{}")
identical(x, list())
#> FALSE
identical(unname(x), list())
#> TRUE
```
=> [#178181135]: better check for empty values in catalog

tests/testthat/test-as-data-frame.R
Not exactly sure what's up, but it's platform dependent, so I'm not super interested in figuring it out.
=> [183690868]: equal instead of identical on data.frame check

R/automation.R
this restores previous functionality but continues to wrap the script in a shoji envlope. Arguably the content type should be `text/plain` and remove the `wrapEntity` here. Opting not to do that initially to avoid possible side effects.
=> declare json

R/folders.R, R/hide-variables.R, R/variable-folder.R
Missed a place where we relied on the old style of public variables in the root of the variables directory instead of using the public folder.
I also inlined the logic of `rootVariableFolder()` because I don't think we ever want to use it directly so we can avoid these bugs.
=> [181049738]: copyFolders uses public folder not root

vignettes/variable-order.Rmd
Vignette:
[Variable Folders and Organization](https://cran.r-project.org/web/packages/crunch/vignettes/variable-order.html)
Section:
Renaming folders and folder contents
=> Fix the ordering of the code snippets so that it matches the text

R/dataset-extract.R, R/dataset.R, R/misc.R, R/variable-catalog.R, man/envOrOption.Rd, tests/testthat/helper.R, tests/testthat/test-dataset-entity.R
Allows users to opt out of some performance problems introduced by the lazy variables catalog.
For context @sluga, early on when I started at crunch, the main variables catalog contained whether each variable was hidden or not. When we added "private" (aka "secure" variables according to the API, though Mike hates this word), we switched to having to navigate the hidden/private variable folder hierarchy to figure out which variables were hidden or private.
This PR:
1. Checks if user wants to get warnings about hidden/private variables before actually checking if the variable is hidden/private so that basic variable access does not require traversing the hidden/private folders. See below for a reprex.
2. Adds a new option `crunch.exclude.hidden.private` that when set to FALSE (not the …
=> Variables cache fixes 184826032

R/misc.R
When using crunch from Shiny apps on a server, we typically don't want the users to share options, we want the options to be session-specific. shiny's shinyOptions and getShinyOption accomplish this when called from within the server function.
=> Use getShinyOption to access options (if ...)

R/dataset.R
Fixes the call to `httpcache::buildCacheKey()` in `getDatasetVariables()`, `getDatasetHiddenVariables()` and `getDatasetPrivateVariables()`. The `extras` argument is now fully spelled out to avoid a partial argument match. With this fix, interactions with a dataset through crunch with the option `warnPartialMatchArgs` set to `TRUE` no longer trigger a warning message.
``` r
options(warnPartialMatchArgs = TRUE)
library(crunch)
set_crunch_opts("crunch.api" = "https://app.crunch.io/api/")
library(httptest)
start_vignette("crunch")
ds <- newDataset(SO_survey, name="Stack Overflow Developer Survey 2017")
dim(ds)
#> [1] 1634   23
```
<sup>Created on 2023-07-19 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
Closes #624.
=> Fix partial argument match in `getDatasetVariables()`

docker/jenkins/Dockerfile.rcrunch
Error is:
```
[2023-11-06T04:34:12.491Z] Step 13/17 : COPY --chown=****:**** ./DESCRIPTION ./Makefile ${HOMEDIR}
[2023-11-06T04:34:12.491Z] When using COPY with more than one source file, the destination must be a directory and end with a /
```
> https://master.ci.crint.net/blue/organizations/jenkins/Build%20Stable%20Images%20for%20our%20k8s%20Backend%20Components/detail/Build%20Stable%20Images%20for%20our%20k8s%20Backend%20Components/9833/pipeline/
=> [186417719]: fix path for copying

tests/testthat/test-append-debug.R, tests/testthat/test-append-subvariables.R, tests/testthat/test-derive-debug.R
For now all tests are commented, but maybe we should just delete them?
Tests fall into broadly 3 categories:
- `tests/testthat/test-append-debug.R` tests that appending 2 datasets with array variables with different aliases, but identically aliased sub variables fails. I think @aminusfu is saying that the new intentional behavior is to allow this because variables can belong to multiple arrays now.
- `tests/testthat/test-append-subvariables.R` tests that appending 2 datasets, one with an array, and the other with unbound versions of the array's sub variables. It expects after appending for the unbound version of the variables to be only included in the arrays. However, now appends will allow 2 versions of the same subvariables to exist.
- `tests/testthat/test-derive-debug.R` tests various …
=> [187316938]: comment out tests affected by reusable subvar codes
